### ISSUE TITLE
Support secondary nav

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/Website#123]
Add a secondary nav to the site so we can have things like:

About -> Jobs
About -> Team

Reports -> 2016
Reports -> 2017

etc.

# Existing
I tried copying the pattern we have on the polling station finder pages:

![screenshot 2018-10-12 08 26 46](https://user-images.githubusercontent.com/242329/46854387-93335b00-cdf8-11e8-8679-dbb8c14a7616.png)

# Not quite right
However, this only really works because the sub-nav items are closely connected to each other (the are all about polling stations). This means they can sit below the heading.

For the "about" section, this doesn't quite work:

![screenshot_2018-10-12_08_19_28](https://user-images.githubusercontent.com/242329/46854445-c1189f80-cdf8-11e8-8fa9-a673a13e0835.png)

## Above the heading?

Putting it above the heading looks fine (for a given value…etc) on the about page:

![screenshot 2018-10-12 08 18 15](https://user-images.githubusercontent.com/242329/46854552-1b196500-cdf9-11e8-9c35-362b17200a87.png)

Bit that's because it's using the wide format pages. The jobs page is (and should) use the blog post narrow format, and then it looks odd:

![screenshot 2018-10-12 08 18 21](https://user-images.githubusercontent.com/242329/46854575-32585280-cdf9-11e8-94c9-24824fb83d72.png)

## Below the nav?

Adding it below the nav groups "things you can press to navigate the site" in to one place, but I'm not convinced it's really visible:

![screenshot 2018-10-12 08 37 58](https://user-images.githubusercontent.com/242329/46854949-52d4dc80-cdfa-11e8-85eb-92e8503cbc81.png)

**Comment by symroe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Turn 'assistant list of things' into a job advert](https://trello.com/c/FSKEJr5b/1411-turn-assistant-list-of-things-into-a-job-advert)

**Comment by JoeMitchell** [comment]
Tricky! 

I think the PSF page is off-putting cos we broke the system to accommodate it. 

If you imagine that the title of your 'Not quite right' screenshot is actually 'About' then 'About, Jobs, Team' would work? 

![image](https://user-images.githubusercontent.com/8096305/46881289-01047480-ce43-11e8-993d-73fc424889dc.png)

_(^^ Obvs the About top nav thing should be pink-underlined rather than Projects!)_

I think this might reflect the website being a bit of a muddle :) 

I attempted a menu.... might require collapsing those 3 poling station finder sub-sub-headers into one page... which might be a disaster.

**Home
About**

- Overview [or About]
- Team
- Jobs

**Projects**

- Overview [or Projects]
- Polling station finder 

1. Overview
2. Use on your website
3. How to send us data

**Reports**

- Overview [or Reports] 
- Impact report 2018 
- Impact report 2017
- Impact report 2016
- WhereDoIVote.co.uk feedback
- [Any other things we've written that i've forgotten]

**Blog
Quests ('Volunteer'?) 
Contact
Donate**


Alternatively, for easiness until we sort this out, however, we could just stick it on the bottom of the About page and not worry about it...

**Comment by JoeMitchell** [comment]
The collapsed secondary-nav is looking a bit odd on me mobile. Could we lose the dots when collapsed? 

![screenshot_20181024-172120](https://user-images.githubusercontent.com/8096305/47483884-3ab98000-d832-11e8-9d64-566af80f0415.png)

**Comment by symroe** [comment]
Refs #126

**Comment by JoeMitchell** [comment]
We also talked about sticking a link to 'Jobs' in the Footer? Or 'We're hiring' — not sure which is better?

**Comment by symroe** [comment]
Put "Jobs" for now. Can change if you like.
