### ISSUE TITLE
Improve how content is presented to users

### ISSUE THREAD

**Issue by VirginiaDooley** [DemocracyClub/Website#376]
Main Nav Bar

- [ ] Remove about
- [ ] Add Reports

Blogs

Reports

**Comment by pmk01** [comment]
Page for press releases/ press coverage

**Comment by VirginiaDooley** [comment]
This was handled in

**Comment by pmk01** [comment]
No problem, at least a quarter of the half-bakery is mine. I don't think this needs new text. There are two things in my mind here:

1. Press coverage. this is simply a new tab under 'about' where we can put links to articles about us. This used to be on the 'about' landing page, but got a bit too long, due to our recent meteoric rise to fame and fortune. Hopefully the list of articles exists somewhere in the ether, because I can't find them right now. There were some new ones I wanted to add, which I also can't find a list of right now. 

2. A 'Research and/or reports and/or briefings and/or press release' page, which is a new tab in the main navigation bar. In practise this can simply be a place for tagged blogs (see eg. [Fawcett Society's example](https://www.fawcettsociety.org.uk/Pages/Category/reports-and-publications). Would require the creation of a couple of new blog tags ('research', 'election data summary', etc). However, this is one of the first things I would like Mevan's opinion on!

Is that all clear? I hope it's the minimum amount of work for the maximum impact! We can ponder on more adventurous things after May...

**Comment by VirginiaDooley** [comment]
@MevanBabakar ^^

**Comment by VirginiaDooley** [comment]
Is this addressed in https://github.com/DemocracyClub/Website/pull/594 and https://github.com/DemocracyClub/Website/pull/590?
