### ISSUE TITLE
'Join our Slack' link is dead

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/Website#88]
https://democracyclub.org.uk/contact/

**Comment by symroe** [comment]
This was caused by me converting our Heroku dyno from a hobby (paid for) to a free one. 

Apparently free dynos don't support SSL (or don't any more) so the https version broke. The http one was always working.

Should be fixed now, at a cost of $7/month. Maybe we should deploy this to another server somewhere? It's a tiny node script.

**Comment by symroe** [comment]
It's odd because it was working earlier this week, but I converted it to free about 2 weeks ago.

**Comment by chris48s** [comment]
seems like quite a good candidate to live on AWS lamda?

**Comment by symroe** [comment]
Can we SSL on Lamda? Via cloud front I guess?

Yep, something to try out!
